version: "3.8"

services:
  node:
    image: node:16
    restart: always
    container_name: appserver
    command: "npm run start"
    env_file: ./.env
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    depends_on:
      - mongo
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - $NGINX_PORT_EXPOSED:$NGINX_PORT_CONTAINER
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file: ./.env
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - ./mongo_data:/data/mongo/db
